### ISSUE TITLE
Wallet suddenly stops auto-receiving transactions

### ISSUE THREAD

**Issue by sol-znn** [hypercore-one/syrius#4] opened 2023-05-06 03:42 UTC
**Describe the bug**
After the wallet has been in use for some time, it will silently stop auto-receiving transactions.
No errors are displayed to the user.
Outbound transactions continue to be processed as expected.
Restarting the wallet temporarily resolves the issue.  

It is unclear at this time what conditions are causing this issue.
   - Potentially switching from embedded node -> public node
   - Potentially leaving the wallet running for some times (hours to days)
   - Potentially locking and unlocking the wallet

I'm currently using Syrius v0.0.6 but Vilkris informed me this was also happening on v0.0.5.
"I encountered issues with the websocket subscriptions dying silently and not receiving updates anymore."

**To Reproduce**
1. Launch Syrius v0.0.6
2. Send any amount of ZTS from Address A to Address B
3. Switch to Address B in Settings

**Expected behavior**
Address B should automatically receive the ZTS funds.

**Desktop**
 - Syrius version: v0.0.6
 - OS: any
 - Commit hash: c996cc404f721b329d12e9a638a149acd6648bf3

**Comment by vilkris4** [comment] 2023-05-17 19:17
I was able to reproduce this issue when my node connection abruptly disconnected while the `AutoReceiveTxWorker` was trying auto receive a transaction. When the worker failed to receive the transaction (an exception was thrown by the ZNN SDK), it apparently failed to add the hash back into the queue, so that it would be retried. When the unreceived transaction hash was attempted to be added into the pool again via the `addHash` function, it failed to do so because the hash was already in the `processedHashes` list.

**Comment by sol-znn** [comment] 2023-05-25 01:47
I've received reports from community members using the v0.1.0 rc on testnet.
Symptoms include:
- Sync status icon quickly changing states (green -> red -> orange -> green)
- Fluctuation of peers (0 <= n <= 6)
- Sudden inability to receive transactions

Temporary workaround: restart Syrius

We may be encountering this issue more frequently due to a low number of nodes on testnet.

**Comment by sol-znn** [comment] 2023-06-02 22:34
Managed to repro this on my devnet

1. Launch Syrius and connect to a node you control (preferably devnet)
2. Run this dart script to generate the transactions
   - [autoreceive_repro.dart.txt](https://github.com/hypercore-one/syrius/files/11639503/autoreceive_repro.dart.txt)
3. Assuming the node host is using Linux, run this every time Syrius receives a tx.
```
#!/bin/bash
kill -9 $(pidof "znnd")
sleep 3
znnd &
```
 
Syrius stopped receiving after the sixth node reset.

**Comment by sol-znn** [comment] 2023-06-03 03:22
Unfortunately, I can still reproduce this issue with the the #24 patch using the steps from my previous post.
It only takes 3-5 node disconnections.

**Comment by vilkris4** [comment] 2023-07-14 16:44
Closing this issue as it should now be fixed in #27.

**Closed as completed by vilkris4** 2023-07-14 16:44 UTC
Labels: bug
